### ISSUE TITLE
shape_predictor_68_face_landmarks.dat dataset

### ISSUE THREAD

**Issue by RubenBenBen** [Urviagrawal/Facial-Landmark-Detector#1]
Hi, I was wondering is your shape_predictor_68_face_landmarks.dat the same as the dlib one which uses iBug data? (https://github.com/davisking/dlib-models) Or did you train your own model with a **different** dataset?

**Comment by Urviagrawal** [comment]
@RubenBenBen Yes, its the same dat file. I haven't trained my own model yet but will soon update with self trained model.
