### ISSUE TITLE
Landmark

### ISSUE THREAD

**Issue by chungyau97** [Urviagrawal/Facial-Landmark-Detector#2]
Can I share my code improvement to you? 
Your code result:
![image](https://user-images.githubusercontent.com/33013947/55126180-3974e200-5147-11e9-94a2-91eef6e3f9c5.png)

After my modification result:
![image](https://user-images.githubusercontent.com/33013947/55125980-90c68280-5146-11e9-93e8-8a0c41af472b.png)

**Comment by Urviagrawal** [comment]
Hey @chungyau97 that's really a good improvement, you can share your code without any doubt. 
And thanks in advance.

**Comment by chungyau97** [comment]
Can I add you somewhere for knowledge sharing?

**Comment by Urviagrawal** [comment]
Yes definitely, it would be really great if I can help someone.

**Comment by chungyau97** [comment]
wechat? line? email?

> Yes definitely, it would be really great if I can help someone.

**Comment by Urviagrawal** [comment]
urviagrawal1993@gmail.com
